bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}
  admin_id: ${BOT_ADMIN_ID}
  invite_expire_days: 7

base:
  url: ${DATABASE_URL}

spring:
  #DATABASE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:${base.url}
  jpa:
    #HIBERNATE
    show-sql: true
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
      use_sql_comments: false
